#    _____ _ _         ____        _ _     _
#  / ____(_) |       |  _ \      (_) |   | |
# | |     _| |_ _   _| |_) |_   _ _| | __| |
# | |    | | __| | | |  _ <| | | | | |/ _` |
# | |____| | |_| |_| | |_) | |_| | | | (_| |
#  \_____|_|\__|\__, |____/ \__,_|_|_|\__,_|
#                __/ |
#               |___/
#
# Current version: 1.0.0
# Copyright (c) ByTRYO, Merry, GhostException and Knerio
#
# ======================================================================================================

farmworld-name = "farmwelt"
farmworld-spawn-name = "farmwelt-spawn"
nether-spawn-name = "nether-spawn"