#    _____ _ _         ____        _ _     _
#  / ____(_) |       |  _ \      (_) |   | |
# | |     _| |_ _   _| |_) |_   _ _| | __| |
# | |    | | __| | | |  _ <| | | | | |/ _` |
# | |____| | |_| |_| | |_) | |_| | | | (_| |
#  \_____|_|\__|\__, |____/ \__,_|_|_|\__,_|
#                __/ |
#               |___/
#
# Current version: 1.0.0
# Copyright (c) ByTRYO, Merry, GhostException and Knerio
#
# ======================================================================================================
#
# This config uses the minimessage format to style text. More about it can be found at
# https://docs.advntr.dev/minimessage/index.html and https://webui.advntr.dev/ .
#
# ======================================================================================================

no-player = "<red>Dazu musst du ein Spieler sein!"
no-permission = "<red>Dazu hast du keine Rechte!"

[money]
balance-own = "<grey>Dein Kontostand beträgt <red>%balance%$<grey>."
balance-other = "<grey>Der Kontostand von <red>%target% <grey>beträgt <red>%balance%$<grey>."
add-success = "<grey>Du hast <red>%target% <grey>einen Betrag von <red>%amount% <grey>hinzugefügt."
add-failure = "<grey>Der Betrag konnte <red>nicht <grey>hinzugefügt werden."
remove-success = "<grey>Du hast <red>%target% <grey>einen Betrag von <red>%amount% <grey>entzogen."
remove-failure = "<grey>Der Betrag konnte <red>nicht <grey>entfernt werden."
set-success = "<grey>Du hast den Kontostand von <red>%target% <grey>auf einen Betrag von <red>%amount% <grey>gesetzt. "
set-failure = "<grey>Der Betrag konnte <red>nicht <grey>gesetzt werden."
clear = "<grey>Du hast das Konto von <red>%target% <grey>geleert."
pay-sender = "<grey>Du hast <red>%target% <grey>einen Betrag von <red>%amount% <grey>überwiesen."
pay-receiver = "<grey>Du hast von <red>%target% <grey>einen Betrag von <red>%amount% <grey>erhalten."
pay-not-enough = "<grey>Du hast nicht genug <red>Guthaben<grey>."
pay-self = "<grey>Du kanst <red>dir <grey>selbst <red>nichts <grey>überweisen."
pay-failure = "<grey>Der Betrag konnte <red>nicht <grey>überwiesen werden."