#    _____ _ _         ____        _ _     _
#  / ____(_) |       |  _ \      (_) |   | |
# | |     _| |_ _   _| |_) |_   _ _| | __| |
# | |    | | __| | | |  _ <| | | | | |/ _` |
# | |____| | |_| |_| | |_) | |_| | | | (_| |
#  \_____|_|\__|\__, |____/ \__,_|_|_|\__,_|
#                __/ |
#               |___/
#
# Current version: 1.0.0
# Copyright (c) ByTRYO, Merry, GhostException and Knerio
#
# ======================================================================================================
#
# This config uses the minimessage format to style text. More about it can be found at
# https://docs.advntr.dev/minimessage/index.html and https://webui.advntr.dev/ .
#
# ======================================================================================================

no-spawn = "<grey>Es wurde <red>kein Spawn <grey>gefunden."

[world]
nether-teleport = "<grey>Du wurdest in das <red>Nether <grey>teleportiert."
farmworld-teleport = "<grey>Du wurdest in die <red>Farmwelt <grey>teleportiert."

[essentials]
heal-self = "<grey>Du hast dich <red>geheilt<gray>."
heal-other = "<grey>Du hast <red>%target% <grey>geheilt."
heal-other-notify = "<grey>Du wurdest von <red>%target% <grey>geheilt."
heal-other-self = "<grey>Du kannst dich <red>nicht selbst <grey>heilen."
feed-self = "<grey>Du hast dich <red>gestättigt<gray>."
feed-other = "<grey>Du hast <red>%target% <grey>gestättigt."
feed-other-notify = "<grey>Du wurdest von <red>%target% <grey>gestättigt."
day = "<grey>Es ist nun <red>Tag<grey>."
fly-allow = "<grey>Du kannst nun <red>fliegen<grey>."
fly-disallow = "<grey>Du kannst nun <red>nicht <grey>mehr <red>fliegen<grey>."
invsee-inventory-name = "<grey>Inventar von <red>%target%"
sign-by-at-date = "<grey>Signiert von <green>%target% <grey>am <yellow>%date%"
sign-no-block = "<grey>Du musst einen <red>Block <grey>in der Haupthand halten."
sign-success = "<grey>Du hast das Item <red>signiert<grey>."
teleport-success-to-player = "<grey> Erfolgreich zu <red>%target% <grey>teleportiert."
teleport-success-for-target = "<grey> Erfolgreich zu <red>%target% <grey>teleportiert."
teleport-send = "<grey>Teleport Anfrage erfolgreich an <red>%target% <grey>versendet."
teleport-request = "<grey>Du hast eine Teleport Anfrage von <red>%target% <grey>erhalten."
teleport-here-send = "<grey>Teleport-here Anfrage erfolgreich an <red>%target% <grey>versendet."
teleport-here-request = "<grey>Du hast eine Teleport-here Anfrage von <red>%target% <grey>erhalten."
teleport-deny = "<grey>Du hast erfolgreich die Teleport Anfrage <red>abgelehnt."
teleport-deny-request = "<grey>Deine Teleport <red>Anfrage <grey>wurde <red>abgelehnt."
teleport-accept = "<red>%target% <grey>hat die Teleport Anfrage <red>akzeptiert."
teleport-request-all = "<grey>Du hast erfolgreich eine Teleport Anfage <red>an alle Spieler <grey>versendet."


[money]
balance-own = "<grey>Dein Kontostand beträgt <red>%balance%$<grey>."
balance-other = "<grey>Der Kontostand von <red>%target% <grey>beträgt <red>%balance%$<grey>."
add-success = "<grey>Du hast <red>%target% <grey>einen Betrag von <red>%amount% <grey>hinzugefügt."
add-failure = "<grey>Der Betrag konnte <red>nicht <grey>hinzugefügt werden."
remove-success = "<grey>Du hast <red>%target% <grey>einen Betrag von <red>%amount% <grey>entzogen."
remove-failure = "<grey>Der Betrag konnte <red>nicht <grey>entfernt werden."
set-success = "<grey>Du hast den Kontostand von <red>%target% <grey>auf einen Betrag von <red>%amount% <grey>gesetzt. "
set-failure = "<grey>Der Betrag konnte <red>nicht <grey>gesetzt werden."
clear = "<grey>Du hast das Konto von <red>%target% <grey>geleert."
pay-sender = "<grey>Du hast <red>%target% <grey>einen Betrag von <red>%amount% <grey>überwiesen."
pay-receiver = "<grey>Du hast von <red>%target% <grey>einen Betrag von <red>%amount% <grey>erhalten."
pay-not-enough = "<grey>Du hast nicht genug <red>Guthaben<grey>."
pay-self = "<grey>Du kanst <red>dir <grey>selbst <red>nichts <grey>überweisen."
pay-failure = "<grey>Der Betrag konnte <red>nicht <grey>überwiesen werden."
