#    _____ _ _         ____        _ _     _
#  / ____(_) |       |  _ \      (_) |   | |
# | |     _| |_ _   _| |_) |_   _ _| | __| |
# | |    | | __| | | |  _ <| | | | | |/ _` |
# | |____| | |_| |_| | |_) | |_| | | | (_| |
#  \_____|_|\__|\__, |____/ \__,_|_|_|\__,_|
#                __/ |
#               |___/
#
# Current version: 1.0.0
# Copyright (c) ByTRYO, Merry, GhostException and Knerio
#
# ======================================================================================================
#
# This config uses the minimessage format to style text. More about it can be found at
# https://docs.advntr.dev/minimessage/index.html and https://webui.advntr.dev/ .
#
# ======================================================================================================

no-player = "<red>Dazu musst du ein Spieler sein!"
no-permission = "<red>Dazu hast du keine Rechte!"

[money]
invalid-usage = "<red>Bitte benutzte <gold>/money <Name><red>!"
balance-own = "<grey>Dein Kontostand beträgt <red>%balance%$<grey>."
balance-other = "<grey>Der Kontostand von <red>%target% <grey>beträgt <red>%balance%$<grey>."